### ISSUE TITLE
Set up basic development environment

### ISSUE THREAD

**Issue by docsteveharris** [CC-HIC/acamedics#3]
- [x] https://www.anaconda.com/distribution/
- [x] https://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language
- [ ] install R http://datascibc.org/Data-Science-for-Docs/ (if not using conda install)
- [x] install R kernel for jupyter
- [x] install hydrogen in atom https://atom.io/packages/hydrogen
- [ ] install cleanEHR from github

```
# remove.packages('cleanEHR')
devtools::install_github('cc-hic/cleanEHR')
library(cleanEHR)

```

**Comment by Roooocher** [comment]
Happy with points ticked
Still a bit uncertain of what anaconda is conceptually?
Hydrogen is running and working

Unsure how to install cleanEHR

**Comment by docsteveharris** [comment]
cleanEHR now in but switched to Rstudio
now need to get data to try out functions
ask steve to send example file to try
